[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
  
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to="https://zurc-claims-tracker.netlify.app/api/*

[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200